name: CI/CD
on:
  push:
    branches:
      - main
      - deploy/test

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Generate mock file
        run: |
          go install github.com/vektra/mockery/v2@v2.20.0
          go generate -v ./...

      - name: Run unit testing
        run: go test -v ./...

      - name: Delete generated mock file
        run: find . -type f -name 'mock_*' -delete

      - name: Build
        run: |
          go build -o mp ./main.go
        
