name: CI/CD
on:
  push:
    branches:
      - main
      - deploy/test

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Generate mock file
        run: |
          go install github.com/vektra/mockery/v2@v2.20.0
          go generate -v ./...

      - name: Run unit testing
        run: go test -v ./...

      - name: Delete generated mock file
        run: find . -type f -name 'mock_*' -delete

  Docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yaml"


#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: |
#            1
#            1
#          build-args: |
#            1.0.0